//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HalloWCF.Client.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bääääh", Namespace="http://schemas.datacontract.org/2004/07/HalloWCF.Host")]
    [System.SerializableAttribute()]
    public partial class Bääääh : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BlubAnzahlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HihihihihField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BlubAnzahl {
            get {
                return this.BlubAnzahlField;
            }
            set {
                if ((this.BlubAnzahlField.Equals(value) != true)) {
                    this.BlubAnzahlField = value;
                    this.RaisePropertyChanged("BlubAnzahl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hihihihih {
            get {
                return this.HihihihihField;
            }
            set {
                if ((object.ReferenceEquals(this.HihihihihField, value) != true)) {
                    this.HihihihihField = value;
                    this.RaisePropertyChanged("Hihihihih");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/WelcheWochentagIstHeute", ReplyAction="http://tempuri.org/IService1/WelcheWochentagIstHeuteResponse")]
        string WelcheWochentagIstHeute();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/WelcheWochentagIstHeute", ReplyAction="http://tempuri.org/IService1/WelcheWochentagIstHeuteResponse")]
        System.Threading.Tasks.Task<string> WelcheWochentagIstHeuteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllTheBääääh", ReplyAction="http://tempuri.org/IService1/GetAllTheBäääähResponse")]
        HalloWCF.Client.ServiceReference1.Bääääh[] GetAllTheBääääh();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllTheBääääh", ReplyAction="http://tempuri.org/IService1/GetAllTheBäääähResponse")]
        System.Threading.Tasks.Task<HalloWCF.Client.ServiceReference1.Bääääh[]> GetAllTheBäääähAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : HalloWCF.Client.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<HalloWCF.Client.ServiceReference1.IService1>, HalloWCF.Client.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public string WelcheWochentagIstHeute() {
            return base.Channel.WelcheWochentagIstHeute();
        }
        
        public System.Threading.Tasks.Task<string> WelcheWochentagIstHeuteAsync() {
            return base.Channel.WelcheWochentagIstHeuteAsync();
        }
        
        public HalloWCF.Client.ServiceReference1.Bääääh[] GetAllTheBääääh() {
            return base.Channel.GetAllTheBääääh();
        }
        
        public System.Threading.Tasks.Task<HalloWCF.Client.ServiceReference1.Bääääh[]> GetAllTheBäääähAsync() {
            return base.Channel.GetAllTheBäääähAsync();
        }
    }
}
